import { Grid, ThemeProvider } from "@mui/material";
import { Inter } from "next/font/google";
import { theme } from "./ThemingContainet/createTheme";
import SidNav from "./SidNavbar/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={inter.className}>
          <Grid container>
            <Grid lg={2}>
              <SidNav></SidNav>
            </Grid>
            <Grid lg={10}>{children}</Grid>
          </Grid>
        </body>
      </ThemeProvider>
    </html>
  );
}
