
"use client"
import { ThemeProvider, createTheme } from '@mui/material'
import './globals.css'
import { Inter } from 'next/font/google'
import {theme} from "./ThemingContainet/createTheme"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {






  return (
    <html lang="en">
      <ThemeProvider theme={theme}><body className={inter.className}>{children}</body></ThemeProvider>
      
    </html>
  )
}
