"use client";
import { Grid, List, ThemeProvider, createTheme } from "@mui/material";
import "./globals.css";
import { Inter } from "next/font/google";
import { theme } from "./ThemingContainet/createTheme";
import SidNav from "./SidNavbar/index";
import Divider from "@mui/material/Divider";
import Toolbar from "@mui/material/Toolbar";
import IconButton from "@mui/material/IconButton";
import ChevronLeftIcon from "@mui/icons-material/ChevronLeft";
import {
  mainListItems,
  secondaryListItems,
} from "./TemplateMui/Deshboard/ListItem";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={inter.className}>
          <Grid container>
            <Grid lg={2}>
              <SidNav></SidNav>
            </Grid>
            <Grid lg={10}>{children}</Grid>
          </Grid>
        </body>
      </ThemeProvider>
    </html>
  );
}
